baseURL = "https://minhDuong27.github.io/fcj-workshop2/"
publishDir = "public"
relativeURLs = true
canonifyURLs = true

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

theme = "hugo-theme-learn"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  themeVariant = "workshop"
  editURL = ""
  description = ""
  author = "thienlh@thienlu.com"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false

[languages]
  [languages.en]
    title = "Internship Report"
    weight = 1
    languageName = "English"

    [[languages.en.menu.shortcuts]]
      name = "<i class='fab fa-facebook'></i> AWS Study Group"
      identifier = "AWS Study Group FB"
      url = "https://www.facebook.com/groups/awsstudygroupfcj/"
      weight = 20

  [languages.vi]
    title = "Báo cáo thực tập"
    weight = 2
    languageName = "Tiếng Việt"

    [[languages.vi.menu.shortcuts]]
      name = "<i class='fab fa-facebook'></i> AWS Study Group"
      identifier = "AWS Study Group FB"
      url = "https://www.facebook.com/groups/awsstudygroupfcj/"
      weight = 20

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
